name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]


jobs:
  linters:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Run all pre-commit hooks on all the files.
      # Getting only staged files can be tricky in case a new PR is opened
      # since the action is run on a branch in detached head state
      - name: Install and Run Flake8
        run: |
          pip install flake8
          flake8

      - name: Install and Run Black
        run: |
          pip install black
          black . --check

      - name: Install and Run isort
        run: |
          pip install isort
          isort . --check

  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Run test coverage
        run: |
            make build
            make run-tests

      - name: Tear down the cli app
        run: make clean

  # With no caching at all the entire ci process takes 4m 30s to complete!
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1

        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push latest from master
        if: ${{ github.ref == 'refs/heads/main' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: enidoshatro/lab:warehouse_cli-latest
      - name: Build and push from merge request branch
        if: ${{ github.ref != 'refs/heads/main' }}
        id: docker_build_branch
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: enidoshatro/lab:warehouse_cli-${{github.sha}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
